name: Sync main/step1 branches

on:
  push:
    branches:
      - steps/1-model-tweaks

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Open pull request
        id: propen
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: ${{ github.ref }}
          base: "steps/2-installing-hotchocolate"
          title: "Mergin step1 into step2"
      - name: Merge pull request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number:  ${{ steps.propen.outputs.number }}
          method: merge