name: Sync main/step1 branches

on:
  push:
    branches:
      - main

jobs:
  create_sync_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: PRCreate
        uses: dequelabs/action-sync-branches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          head: 'main'
          base: 'steps/1-model-tweaks'
          pr-title: 'Merge main into step1'
          pr-labels: automerge
      - name: PRMerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "merge"
          MERGE_LABELS: "automerge"