name: Sync main/step1 branches

on:
  push:
    branches:
      - main

jobs:
  create_sync_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: propen
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "main"
          TO_BRANCH: "steps/1-model-tweaks"
      - name: prmerge
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ PULL_REQUEST_NUMBER }}
          method: merge