name: Sync main/step1 branches

on:
  push:
    branches:
      - main

jobs:
  create_sync_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: "steps/1-model-tweaks"
          branch: "main"
