name: Sync main/step1 branches

on:
  push:
    branches:
      - main

jobs:
  create_sync_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: propen
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: ${{ github.ref }}
          base: "steps/1-model-tweaks"
      - name: prmerge
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number:  ${{ steps.propen.outputs.number }}
          method: merge