name: Sync main/step1 branches

on:
  push:
    branches:
      - 'steps/1-model-tweaks'

jobs:
  create_sync_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: dequelabs/action-sync-branches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          head: 'steps/1-model-tweaks'
          base: 'steps/2-installing-hotchocolate'
          pr-title: 'Merge step1 into step2'
          pr-labels: automerge